name: qalculate
version: '2.6.2'
summary: The ultimate desktop calculator
description: |
  Qalculate! is a multi-purpose cross-platform desktop calculator. It is simple
  to use but provides power and versatility normally reserved for complicated
  math packages, as well as useful tools for everyday needs (such as currency
  conversion and percent calculation). Features include a large library of
  customizable functions, unit calculations and conversion, symbolic calculations
  (including integrals and equations), arbitrary precision, interval arithmetic,
  plotting, and a user-friendly interface.

grade: stable
confinement: strict

plugs:
  gnome-3-26-1604:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-26-1604
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

slots:
  dbus-qalculate:
    interface: dbus
    name: org.gtk.qalculate
    bus: session

apps:
  qalc:
    environment:
        DISABLE_WAYLAND: 1
        GNUPLOT_DRIVER_DIR: $SNAP/libexec/gnuplot/5.2
    command: desktop-launch qalc
    plugs: [network]
  gtk:
    environment:
        DISABLE_WAYLAND: 1
        GNUPLOT_DRIVER_DIR: $SNAP/libexec/gnuplot/5.2
    command:  desktop-launch qalculate-gtk
    plugs: [unity7, network, home]
  gnuplot:
    environment: 
        GNUPLOT_DRIVER_DIR: $SNAP/libexec/gnuplot/5.2
    command: desktop-launch gnuplot
    plugs: [unity7, home]

parts:
  libqalculate:
    source: https://github.com/Qalculate/libqalculate.git
    source-tag: v2.6.2
    plugin: autotools
    build-packages:
      - libncurses5-dev
      - libreadline-dev
      - libcurl4-gnutls-dev
      - libicu-dev
      - libxml2-dev
      - libgmp-dev
      - libmpfr-dev
      - intltool
      - doxygen
    stage-packages:
      - libxml2
    override-build: |
      for p in ../../../patches/lib/*.patch
      do
        cat $p | patch -p1
      done
      snapcraftctl build
      echo Stripping qalc
      strip $SNAPCRAFT_PART_INSTALL/bin/qalc
    prime:
      - -include
      - -lib/pkgconfig
      - -lib/*.a
      - -share/doc
      - -usr/share/doc
      - -usr/share/lintian

  qalculate-gtk:
    source: https://github.com/Qalculate/qalculate-gtk.git
    source-tag: v2.6.2
    plugin: autotools
    build-packages:
      - libgmp-dev
      - libgtk-3-dev
      - libxml2-dev
      - intltool
    override-build: |
      for p in ../../../patches/gui/*.patch
      do
        cat $p | patch -p1
      done
      snapcraftctl build
      echo Stripping qalculate-gtk
      strip $SNAPCRAFT_PART_INSTALL/bin/qalculate-gtk
    after:
      - libqalculate
      - desktop-gnome-platform
    prime:
      - -share/applications
      - -share/doc

  gnuplot:
    source: https://sourceforge.net/projects/gnuplot/files/gnuplot/5.2.4/gnuplot-5.2.4.tar.gz
    plugin: autotools
    configflags:
      - --without-lasergnu
      - --with-png
      - --with-gd
      - --without-lisp-files
      - --without-linux-vga
      - --with-readline=bsd
      - --disable-wxwidgets
    build-packages:
      - libcerf-dev
      - libcairo2-dev
      - libedit-dev
      - libgd-dev
      - liblua5.1-dev
      - lua5.1
      - libpango1.0-dev
      - libpng-dev
      - libx11-dev
      - libxt-dev
      - pkg-config
      - zlib1g-dev
    prime:
      - -share/applications
      - -share/doc
      - -share/man
    after:
      - desktop-gnome-platform
    override-build: |
      snapcraftctl build
      echo Stripping gnuplot
      strip $SNAPCRAFT_PART_INSTALL/bin/gnuplot
      strip $SNAPCRAFT_PART_INSTALL/libexec/gnuplot/5.2/gnuplot_x11

  workaround:
    plugin: nil
    stage-packages:
      - libgtk-3-0
    prime:
      - "-*"

